### PR TITLE
Filter out junk files

### LINKED ISSUE #247: Error with Thumbs.db on Windows
Hi,

I use imagemin-cli 3.0.0 with `imagemin image/* --out-dir image` but i got the following error:

```
Error: Error in file: image/Thumbs.db
EPERM: operation not permitted, open 'myFolder\image\Thumbs.db'
```
I [see ](https://en.wikipedia.org/wiki/Windows_thumbnail_cache) that it comes from the thumbnails generated by Windows 7 but I think this file should be automaticaly black-listed from the list of the files to process.

### PR DESCRIPTION
**Pull request by tprobinson**
Fixes #247. A test is included, not sure if I did it right.

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -55,7 +56,9 @@ module.exports = (input, output, opts) => {
 	opts = Object.assign({plugins: []}, opts);
 	opts.plugins = opts.use || opts.plugins;
 
-	return globby(input, {nodir: true}).then(paths => Promise.all(paths.map(x => handleFile(x, output, opts))));
+	return globby(input, {nodir: true})
+		.then(paths => Promise.resolve(paths.filter(path => junk.not(path))))
```
Comment (sindresorhus) [inline index.js]: The `Promise.resolve` call is moot and you can just put the filter logic in the same `.then` as the `Promise.all` call.

**Comment by tprobinson** [comment]
Sorry it took me so long to get back to this! It's all synced up with master, and I rewrote the test to actually do something useful.

File: index.js [hunk 2]
```diff
@@ -53,7 +54,8 @@ module.exports = (input, output, options) => {
 	options = Object.assign({plugins: []}, options);
 	options.plugins = options.use || options.plugins;
 
-	return globby(input, {onlyFiles: true}).then(paths => Promise.all(paths.map(x => handleFile(x, output, options))));
+	return globby(input, {onlyFiles: true})
+		.then(paths => Promise.all(paths.reduce((acc, x) => junk.is(path.basename(x)) ? acc : acc.concat(handleFile(x, output, options)), [])));
```
Comment (sindresorhus) [inline index.js]: Using `reduce` here just makes the code much less readable. Would be better to use `filter`.
